import Cards from '@/Components/Cards'
import { Color } from '@/utils/colors'
import { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { Box } from '@/Components/Box'

const Title = styled.h1`
  font-size: 4em;
  color: ${Color.Black};
  @media (max-width: 768px) {
    font-size: 2em;
    width: 400px;
  }
`

const Home: NextPage = () => {
  const title = `Hi, I'm Jake`

  return (
    <>
      <Head>
        <title>Jake Edgar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Title>{title}</Title>
      <br />
      <Box className='card-body'>
        I am a <strong>Senior Full Stack Software Engineer</strong>, with a passion for <strong>bold beautiful designs</strong> and{' '}
        <strong>blazing load speeds</strong>, but my real super power is bringing people together as a team.
      </Box>
      <br />
      <Cards />
      <br />
      <Title>My Projects</Title>
      <br />
      <div
        style={{
          display: 'flex',
          width: '800px',
          height: '600px',
          justifyContent: 'center',
          alignItems: 'center',
          border: '1px solid black',
          borderRadius: '8px',
        }}
      >
        Test Content
      </div>
      <br />
    </>
  )
}

export default Home
